<?php

//Conecci? con el WHMCS
function conectarWHMCS($marca)
{
	switch($marca)
	{
		case "hosting": $link=mysqli_connect("190.96.85.228", "hostingc_fabian", "hosting.,", "hostingc_whmcsnew"); break;
		case "planeta": $link=mysqli_connect("201.148.105.50","igor_userph","whm*2008*.,","igor_whmph"); break;
		case "hcenter": $link=mysqli_connect("190.96.85.114","hcenter_admin","Planeta*1910Center","hcenter_whmcs"); break;
		case "planetape": $link=mysqli_connect("201.148.107.40","planetco_user","admin7440","planetco_whmcs"); break;
		case "inka": $link=mysqli_connect("201.148.107.40","inkahost_user","inka_.,2013","inkahost_whmcs"); break;
		case "ninja": $link=mysqli_connect("panel.ninjahosting.cl","panelnin_ting14","]^k5[OVvr!PZ","panelnin_whmcs"); break;
		case "hostingpro": $link=mysqli_connect("panel.hostingpro.com.co","panelhpr_alce","_DA{cRav1y1,","panelhpr_alce"); break;
	}
	
	if (mysqli_connect_errno()) 
	{
		printf("Ha fallado la conexi? con el WHMCS: %s\n", mysqli_connect_error());
		exit();
	}
	
	return $link;
}

//Conección con BBDD ASterisk
function conectarAsterisk($data_base)
{
	$link = mysqli_connect("190.153.249.226", "root", "hosting.,12", $data_base);
	if (mysqli_connect_errno()) 
	{
		printf("Ha fallado la conexión con Asterisk ($data_base): %s\n", mysqli_connect_error());
		exit();
	}
	
	return $link;
}

//Conecta con la base de datos que almacena las calificaciones mensuales
function conectarBDCalificaciones()
{
	$link=mysqli_connect("localhost", "sistemas_alvaro", "alv15963", "sistemas_iscol");
	
	if (mysqli_connect_errno()) 
	{
		printf("Ha fallado la conexión con la BBDD de ISCOL: %s\n", mysqli_connect_error());
		exit();
	}
	
	return $link;
}

//Comprueba si un mail de chat contiene o no encuesta
function contieneEncuesta($texto)
{
	if(strpos($texto,'Post Chat Survey') !== false)
		return true;
	return false;
}

//Devuelve s?o la encuesta del mail de chat
function extraerEncuesta($texto)
{
	$inicio = strpos($texto,'Post Chat Survey');
	$fin = strpos($texto,'This transcript email message was automatically generated by',$inicio);
	$largo = $fin - $inicio;
	
	return substr($texto,$inicio,$largo);
}

//Obtiene el operador a partir del asunto del correo
function obtenerOperador($texto)
{
	if(strpos($texto,'Operators:') !== false)
	{
		$inicio = strpos($texto,'Operators:') + 11;
		$fin = strpos($texto,',',$inicio);
		$largo = $fin - $inicio;
		
		$operador = substr($texto,$inicio,$largo);
	}
	else if(strpos($texto,'Operator:') !== false)
	{
		$inicio = strpos($texto,'Operator:') + 10;
		$fin = strpos($texto,'.',$inicio);
		$largo = $fin - $inicio;
		
		$operador = substr($texto,$inicio,$largo);
	}
	else
	{
		$operador = "~ No Contestado";
	}
		
	$operador = str_replace("?= =?ISO-8859-1?Q?","",$operador);
	
	if($operador == "Claudio Cuevas") //TODO: cambiar esto
		$operador = "Claudio Cuevas";
	else if($operador == "Humberto Reina")
	{
		$operador = "Jhonathan Quiñones";
		return $operador;
	}
	else if($operador == "Marcela Reina")
	{
		$operador = "Lina Quiñones";
		return $operador;
	}
	
	return utf8_encode($operador);
}

//Obtiene el valor de amabilidad del operador de la encuesta de chat
function obtenerAmabilidad($texto)
{
	$inicio = strpos($texto,'Politeness:');
	$inicio = strpos($texto,'value-td',$inicio) + 10;
	
	if($inicio == 10)
		$inicio = strpos($texto,'Politeness:') + 12;
	
	return substr($texto,$inicio,1);	
}

//Obtiene el valor de eficiencia del operador de la encuesta de chat
function obtenerEficiencia($texto)
{
	$inicio = strpos($texto,'Proficiency:');
	$inicio = strpos($texto,'value-td',$inicio) + 10;
	
	if($inicio == 10)
		$inicio = strpos($texto,'Proficiency:') + 13;
		
	return substr($texto,$inicio,1);
}

//Actualiza las calificaciones de un operador
function actualizarEvaluaciones($evaluaciones,$operador,$amabilidad,$eficiencia,$cantidad = 1)
{
	if(array_key_exists($operador,$evaluaciones))
	{
		$evaluaciones[$operador]['amabilidad'] = (($evaluaciones[$operador]['amabilidad'] * $evaluaciones[$operador]['cantidad']) + $amabilidad) / ($evaluaciones[$operador]['cantidad'] + 1);
		$evaluaciones[$operador]['eficiencia'] = (($evaluaciones[$operador]['eficiencia'] * $evaluaciones[$operador]['cantidad']) + $eficiencia) / ($evaluaciones[$operador]['cantidad'] + 1);
		$evaluaciones[$operador]['cantidad'] = $evaluaciones[$operador]['cantidad'] + $cantidad;
	}
	else
	{
		$evaluaciones[$operador] = array('amabilidad' => (double)$amabilidad,'eficiencia' => (double)$eficiencia,'cantidad' => $cantidad);
	}
	
	return $evaluaciones;
}

//Aumenta en la cantidad de contestados de un operador
function aumentarCantidadContestados($evaluaciones,$operador,$cantidad)
{
	if(array_key_exists($operador,$evaluaciones))
		$evaluaciones[$operador]['cantidad_contestados'] = $evaluaciones[$operador]['cantidad_contestados'] + $cantidad;
	else
		$evaluaciones[$operador] = array('amabilidad' => -1,'eficiencia' => -1,'cantidad' => 0, 'cantidad_contestados' => $cantidad);
	
	return $evaluaciones;
}

//Calcula el valor TOTAl del grupo de operadores
function calcularTotal($evaluaciones)
{
	if(count($evaluaciones) == 0)
	{
		$evaluaciones["TOTAL"] = array('amabilidad' => 0,'eficiencia' => 0,'cantidad' => 0,'cantidad_contestados' => 0);
		return $evaluaciones;
	}
		
	$amabilidad = 0;
	$eficiencia = 0;
	$cantidad = 0;
	$cantidad_contestados = 0;
	
	foreach($evaluaciones as $operador=>$detalles)
	{
		if($operador != "Porcentaje de Respuesta" && $operador != "Total recibidos")
		{
			$amabilidad += $detalles["amabilidad"] * $detalles["cantidad"];
			$eficiencia += $detalles["eficiencia"] * $detalles["cantidad"];
			$cantidad += $detalles["cantidad"];
			$cantidad_contestados += $detalles["cantidad_contestados"];
		}
	}
	
	$amabilidad = $amabilidad / $cantidad;
	$eficiencia = $eficiencia / $cantidad;

	$evaluaciones["TOTAL"] = array('amabilidad' => (double)$amabilidad,'eficiencia' => (double)$eficiencia,'cantidad' => $cantidad,'cantidad_contestados' => $cantidad_contestados);
	
	return $evaluaciones;
}

//Devuelve el nombre del mes en ingles, en 3 letras
function nombreMesIngles($num)
{
	switch($num)
	{
		case 0:return "Dec";break;
		case 1:return "Jan";break;
		case 2:return "Feb";break;
		case 3:return "Mar";break;
		case 4:return "Apr";break;
		case 5:return "May";break;
		case 6:return "Jun";break;
		case 7:return "Jul";break;
		case 8:return "Aug";break;
		case 9:return "Sep";break;
		case 10:return "Oct";break;
		case 11:return "Nov";break;
		case 12:return "Dec";break;
	}
}

//Devuelve el nombre del mes completo en español
function nombreMesEspañol($num)
{
	switch($num)
	{
		case 0:return "Diciembte";break;
		case 1:return "Enero";break;
		case 2:return "Febrero";break;
		case 3:return "Marzo";break;
		case 4:return "Abril";break;
		case 5:return "Mayo";break;
		case 6:return "Junio";break;
		case 7:return "Julio";break;
		case 8:return "Agosto";break;
		case 9:return "Septiembre";break;
		case 10:return "Octubre";break;
		case 11:return "Noviembre";break;
		case 12:return "Diciembre";break;
	}
}

//Define los rangos para que una calificacion sea considerada muy baja,baja,alta o muy alta
function claseCalificacion($calificacion)
{
	if($calificacion >= 3.5)
		return "muy_alto";
	else if($calificacion >= 3 && $calificacion < 3.5)
		return "alto";
	else if($calificacion >= 2 && $calificacion < 3)
		return "bajo";
	else if($calificacion < 2 && $calificacion > 0)
		return "muy_bajo";
	else if($calificacion == "-")
		return "sin_calificacion";
}

//Recalcula los valores de las calificaciones luego de usar unir arreglos recursivamente
function eliminarRecursividad($array)
{
	$respuesta=array();
	$total_recibido = 0;
	
	foreach($array as $operador=>$detalles)
	{
		if ($operador == "Total recibidos")
			foreach($detalles as $valor)
				$total_recibido += $valor;
		else if ($operador != "Porcentaje de Respuesta")
		{
			$amabilidad = 0;
			$eficiencia = 0;
			$cantidad = 0;
			$cantidad_contestados = 0;
			
			if (count($detalles['amabilidad']) == 1)
			{
				$amabilidad += $detalles['amabilidad'] * $detalles['cantidad'];
				$eficiencia += $detalles['eficiencia'] * $detalles['cantidad'];
				$cantidad += $detalles['cantidad'];
				$cantidad_contestados += $detalles['cantidad_contestados'];
			}
			else
				for($i=0; $i < count($detalles['amabilidad']); $i++)
				{
					$amabilidad += $detalles['amabilidad'][$i] * $detalles['cantidad'][$i];
					$eficiencia += $detalles['eficiencia'][$i] * $detalles['cantidad'][$i];
					$cantidad += $detalles['cantidad'][$i];
					$cantidad_contestados += $detalles['cantidad_contestados'][$i];
				}
			
			$amabilidad = $cantidad != 0 ? $amabilidad / $cantidad : -1;
			$eficiencia = $cantidad != 0 ? $eficiencia / $cantidad : -1;
			
			$respuesta[$operador]['amabilidad'] = $amabilidad;
			$respuesta[$operador]['eficiencia'] = $eficiencia;
			$respuesta[$operador]['cantidad'] = $cantidad;
			$respuesta[$operador]['cantidad_contestados'] = $cantidad_contestados;
		}
	}
	
	$respuesta["Porcentaje de Respuesta"] = "";
	$respuesta["Total recibidos"] = $total_recibido;
		
	return $respuesta;
}

//Dibuja la tabla con los valores de las evaluaciones
function crearTabla($evaluaciones,$modo)
{
	if($modo == "nota_final")
		echo "<td style='vertical-align:top'><table class='tabla_secundaria'><tr><th>Operador</th><th>Nota Final</th><th>Cantidad Encuestas</th><th>Cantidad Contestados</th></tr>";
	else if($modo == "nota_detalle")	
		echo "<td style='vertical-align:top'><table class='tabla_secundaria'><tr><th>Operador</th><th>Amabilidad</th><th>Eficiencia</th><th>Cantidad Encuestas</th><th>Cantidad Contestados</th></tr>";
		
	foreach($evaluaciones as $operador=>$detalles)
	{
		$amabilidad = round($detalles["amabilidad"],1) < 0 ? "-" : round($detalles["amabilidad"],1);
		$eficiencia = round($detalles["eficiencia"],1) < 0 ? "-" : round($detalles["eficiencia"],1);
		$nota_final = ($detalles["amabilidad"] < 0 && $detalles["eficiencia"] < 0) ? '-' : round((($detalles["amabilidad"] * 0.3) + ($detalles["eficiencia"] * 0.7)),1);
		
		if($modo == "nota_final")
		{
			if($operador == "TOTAL")
				echo "<tr class = 'total'><th>{$operador}</th><th>$nota_final</th><th>{$detalles["cantidad"]}</th><th>{$detalles["cantidad_contestados"]}</th></tr>";
			else if($operador == 'Porcentaje de Respuesta')
				echo "<tr class = 'porcentaje' ><th>{$operador}</th><th colspan='3'>{$detalles}%</th></tr>";
			else if($operador == 'Total recibidos')
				echo "<tr class = 'porcentaje' ><th>{$operador}</th><th colspan='3'>{$detalles}</th></tr>";
			else
				echo "<tr><td id='{$operador}' class='operador'>{$operador}</td><td class = '".claseCalificacion($nota_final)."'>$nota_final</td><td id='{$operador}' class='operador'>{$detalles["cantidad"]}</td><td id='{$operador}' class='operador'>{$detalles["cantidad_contestados"]}</td></tr>";
		}
		else if($modo == "nota_detalle")
		{
			if($operador == "TOTAL")
				echo "<tr class = 'total'><th>{$operador}</th><th>$amabilidad</th><th>$eficiencia</th><th>{$detalles["cantidad"]}</th><th>{$detalles["cantidad_contestados"]}</th></tr>";
			else if($operador == 'Porcentaje de Respuesta')
				echo "<tr class = 'porcentaje' ><th>{$operador}</th><th colspan='4'>{$detalles}%</th></tr>";
			else if($operador == 'Total recibidos')
				echo "<tr class = 'porcentaje' ><th>{$operador}</th><th colspan='4'>{$detalles}</th></tr>";
			else
				echo "<tr><td id='{$operador}' class='operador'>{$operador}</td><td class = '".claseCalificacion($amabilidad)."'>$amabilidad</td><td class = '".claseCalificacion($eficiencia)."'>$eficiencia</td><td id='{$operador}' class='operador'>{$detalles["cantidad"]}</td><td id='{$operador}' class='operador'>{$detalles["cantidad_contestados"]}</td></tr>";
		}
	}
	echo "</table></td>";
}

//Calcula las calificaciones leyendo los correos de chat@hosting.cl
function obtenerCalificacionesChat($mes,$año)
{
	$año_inicio = $año;
	$año_fin = ($mes == 12 ? $año + 1 : $año);

	$mes_inicio_ingles = nombreMesIngles($mes);
	$mes_fin_ingles = nombreMesIngles(($mes + 1)%12);

	$hostname = "{mail.hosting.cl/notls}";
	$username = "chat@hosting.cl";
	$password = "ignacia.,14";

	$evaluaciones_chat = array();

	$inbox = imap_open($hostname,$username,$password) or die('Ha fallado la conexión con el Mail: ' . imap_last_error());
	$emails = imap_search($inbox, 'SINCE "1 '.$mes_inicio_ingles.' '.$año_inicio.'" BEFORE "1 '.$mes_fin_ingles.' '.$año_fin.'"'); //Para Mayo-14 usar: 'SINCE "1 May 2014" BEFORE "1 Jun 2014"'
	
	$chats_cerrados = 0;
	$chats_con_encuesta = 0;
	
	if($emails !== false)
	{
		foreach($emails as $email_number)
		{
			$message = imap_body($inbox,$email_number);
			$chats_cerrados++;
			
			if(contieneEncuesta($message))
			{
				$chats_con_encuesta++;
				$overview = imap_fetch_overview($inbox,$email_number);
				
				$subject = iconv_mime_decode($overview[0]->subject);
				//$fecha = $overview[0]->date;
				// $subject = str_replace("_"," ",$subject);
				// $subject = str_replace("=F1","?,$subject);
				// $subject = str_replace("'","?",$subject);
				$encuesta = extraerEncuesta($message);
				
				$operador = obtenerOperador($subject);

				$operador = trim($operador);
				$amabilidad = obtenerAmabilidad($encuesta);
				$eficiencia = obtenerEficiencia($encuesta);
				$evaluaciones_chat = actualizarEvaluaciones($evaluaciones_chat,$operador,$amabilidad,$eficiencia);
				$evaluaciones_chat = aumentarCantidadContestados($evaluaciones_chat,$operador,1);
			}
			else
			{
				$overview = imap_fetch_overview($inbox,$email_number);
				
				$subject = iconv_mime_decode($overview[0]->subject);
				// $subject = str_replace("_"," ",$subject);
				// $subject = str_replace("=F1","?,$subject);
				// $subject = str_replace("'","?",$subject);
				
				$operador = obtenerOperador($subject);
				$operador = str_replace("= =?ISO-8859-1?Q?","",$operador);
				$operador = str_replace("?=	=?iso-8859-1?Q?","",$operador);
				$operador = str_replace("?","",$operador);
				$operador = trim($operador);
				if($operador != "")
					$evaluaciones_chat = aumentarCantidadContestados($evaluaciones_chat,$operador,1);
				else
					$evaluaciones_chat = aumentarCantidadContestados($evaluaciones_chat,'~ No asignado',1);
			}
			// if($operador == "~ No Contestado")
			// 	echo "<div style='border:1px solid black'>$message</div>";
		}
	}
	
	ksort($evaluaciones_chat);
	$evaluaciones_chat = calcularTotal($evaluaciones_chat);
	if($chats_cerrados != 0)
		$evaluaciones_chat['Porcentaje de Respuesta'] = round(($chats_con_encuesta/$chats_cerrados)*100,2);
	else
		$evaluaciones_chat['Porcentaje de Respuesta'] = 0;
	$evaluaciones_chat['Total recibidos'] = $chats_cerrados;
	
	imap_close($inbox);
	
	return $evaluaciones_chat;
}

//Calcula las calificaciones desde los WHMCS de las marcas
function obtenerCalificacionesTicket($mes,$año)
{
	$marcas = array("hosting","planeta","hcenter","planetape","inka","ninja");
	$evaluaciones_tickets = array();
	
	$tickets_cerrados = 0;
	$tickets_con_encuesta = 0;
	
	foreach($marcas as $marca)
	{
		$link = conectarWHMCS($marca);
		$query = "SELECT * FROM(
					SELECT A.admin,COUNT(DISTINCT A.tid) AS totaltickets 
					FROM tblticketreplies as A, tbltickets as B WHERE 
					MONTH(A.date) = $mes
					AND YEAR(A.date) = $año
					AND A.admin!='' 
					AND A.tid = B.id
					AND B.status = 'Closed'
					GROUP BY A.admin) as ticketsporusuario";
		$result = mysqli_query($link,$query);
		while($row = mysqli_fetch_array($result, MYSQLI_ASSOC))
		{	
			$row["admin"] = str_replace("  ", " ", $row["admin"]);

			if($row["admin"] == "Cristian Casamayor")
				$row["admin"] = "Alfredo Sepulveda";
			if (preg_match('!!u', $row["admin"]))
				$row["admin"] = $row["admin"];
			else 
			   $row["admin"] = utf8_encode($row["admin"]);
			   
			$evaluaciones_tickets = aumentarCantidadContestados($evaluaciones_tickets,$row["admin"],$row["totaltickets"]);
			$tickets_cerrados += $row["totaltickets"];
		}
		
		$query = "SELECT SUM(cantidad) as total FROM
					(SELECT CONCAT(B.firstname,' ',B.lastname) as nombre, AVG(FLOOR(A.rating/10)) as amabilidad, AVG(A.rating%10) as eficiencia, COUNT(CONCAT(B.firstname,' ',B.lastname)) as cantidad 
					FROM tblticketfeedback as A,tbladmins as B 
					WHERE MONTH(A.datetime) = $mes
					AND YEAR(A.datetime) = $año
					AND A.adminid = B.id
					GROUP BY firstname
					ORDER BY datetime ASC) as tickets_encuestados";
		$result = mysqli_query($link,$query);
		
		if(!$result)
			echo "$marca - $query";
		
		$row = mysqli_fetch_array($result, MYSQLI_ASSOC);	
		$tickets_con_encuesta += $row["total"];
		
		mysqli_close($link);
	}

	foreach($marcas as $marca)
	{
		$link = conectarWHMCS($marca);
		
		$query = "SELECT CONCAT(B.firstname,' ',B.lastname) as nombre, AVG(FLOOR(A.rating/10)) as amabilidad, AVG(A.rating%10) as eficiencia, COUNT(CONCAT(B.firstname,' ',B.lastname)) as cantidad 
					FROM tblticketfeedback as A,tbladmins as B 
					WHERE MONTH(A.datetime) = $mes
					AND YEAR(A.datetime) = $año
					AND A.adminid = B.id
					GROUP BY firstname
					ORDER BY datetime ASC";

		$result = mysqli_query($link,$query);
		while($row = mysqli_fetch_array($result, MYSQLI_ASSOC))
		{
			if($row["nombre"] == "Cristian Casamayor")
				$row["nombre"] = "Alfredo Sepulveda";
			if (preg_match('!!u', $row["nombre"]))
				$nombre_operador = $row["nombre"];
			else 
			   $nombre_operador = utf8_encode($row["nombre"]);
			   
			$evaluaciones_tickets = actualizarEvaluaciones($evaluaciones_tickets,$nombre_operador,$row["amabilidad"],$row["eficiencia"],$row["cantidad"]);
		}
		
		mysqli_close($link);
	}
					
	ksort($evaluaciones_tickets);
	$evaluaciones_tickets = calcularTotal($evaluaciones_tickets);
	if($tickets_cerrados != 0)
		$evaluaciones_tickets['Porcentaje de Respuesta'] = round(($tickets_con_encuesta/$tickets_cerrados)*100,2);
	else
		$evaluaciones_tickets['Porcentaje de Respuesta'] = 0;
	$evaluaciones_tickets['Total recibidos'] = $tickets_cerrados;
	
	return $evaluaciones_tickets;
}

//Calcula las calificaciones telefonicas
function obtenerCalificacionesTelefono($mes,$año)
{
	$evaluaciones_telefono = array();
	
	$telefono_cerrados = 0;
	$telefono_con_encuesta = 0;
	
	$link = conectarAsterisk("ASTDB");
	$query = "SELECT SUBSTR(dstchannel,5,3) as agente, count(*) as cantidad FROM cdr 
				WHERE MONTH(end) = $mes AND YEAR(end) = $año
				AND dstchannel != '' AND duration > 40 AND dcontext != 'interno'
				AND src != '' AND dcontext != 'from-pstn'
				AND SUBSTR(dstchannel,5,3) != 'I/i' AND SUBSTR(dstchannel,5,3) != 'l/9'
				GROUP BY agente";
	$result = mysqli_query($link,$query);
	while($row = mysqli_fetch_array($result, MYSQLI_ASSOC))
	{
		$evaluaciones_telefono = aumentarCantidadContestados($evaluaciones_telefono,NombreOperador($row["agente"]),$row["cantidad"]);
		$telefono_cerrados += $row["cantidad"];
	}
	
	mysqli_close($link);
	
	$link = conectarAsterisk("encuesta");
	$query = "SELECT agente,AVG(nota1) as amabilidad,AVG(nota2) as eficiencia,COUNT(agente) as cantidad FROM encuestas WHERE MONTH(DATE) = $mes AND YEAR(DATE) = $año GROUP BY agente";
	$result = mysqli_query($link,$query);

	while($row = mysqli_fetch_array($result, MYSQLI_ASSOC))
	{
		$evaluaciones_telefono = actualizarEvaluaciones($evaluaciones_telefono,NombreOperador($row["agente"]),$row["amabilidad"],$row["eficiencia"],$row["cantidad"]);
		$telefono_con_encuesta += $row["cantidad"];
	}
	
	mysqli_close($link);
					
	ksort($evaluaciones_telefono);
	$evaluaciones_telefono = calcularTotal($evaluaciones_telefono);
	if($telefono_cerrados != 0)
		$evaluaciones_telefono['Porcentaje de Respuesta'] = round(($telefono_con_encuesta/$telefono_cerrados)*100,2);
	else
		$evaluaciones_telefono['Porcentaje de Respuesta'] = 0;
	$evaluaciones_telefono['Total recibidos'] = $telefono_cerrados;
	
	return $evaluaciones_telefono;
}

//Combina las calificaciones de chat,ticket y telefono
function obtenerCalificacionesTotal($evaluaciones_chat,$evaluaciones_tickets,$evaluaciones_telefono)
{
	$evaluaciones_total = $evaluaciones_chat;
	$evaluaciones_total = array_merge_recursive($evaluaciones_total,$evaluaciones_tickets,$evaluaciones_telefono);
	unset($evaluaciones_total['TOTAL']);
	
	$evaluaciones_total = eliminarRecursividad($evaluaciones_total);

	ksort($evaluaciones_total);
	
	$evaluaciones_total = calcularTotal($evaluaciones_total);
	
	if($evaluaciones_total["Total recibidos"] != 0)
		$evaluaciones_total['Porcentaje de Respuesta'] = round(($evaluaciones_total["TOTAL"]['cantidad']/$evaluaciones_total["Total recibidos"])*100,2);
	else
		$evaluaciones_total['Porcentaje de Respuesta'] = 0;
	
	return $evaluaciones_total;
}

//Almacena las calificaciones en la base de datos
function guardarCalificaciones($evaluaciones_chat,$evaluaciones_ticket,$evaluaciones_telefono,$evaluaciones_total,$mes,$año)
{
	$link = conectarBDCalificaciones();
	
	foreach($evaluaciones_chat as $operador => $valores)
	{
		$operador = utf8_decode($operador);
		if(!isset($valores["amabilidad"]) && !isset($valores["eficiencia"]) && !isset($valores["cantidad"]))
			$cantidad = (double)$valores;
		else
		{
			$amabilidad = round($valores["amabilidad"],1);
			$eficiencia = round($valores["eficiencia"],1);
			$cantidad = round($valores["cantidad"],1);
			$cantidad_contestados = round($valores["cantidad_contestados"],1);
		}		
		
		$query = "INSERT INTO calificaciones (operador,amabilidad_chat,eficiencia_chat,cantidad_chat,cantidad_contestados_chat,fecha) 
					VALUES ('$operador',$amabilidad,$eficiencia,$cantidad,$cantidad_contestados,'$mes-$año')
					ON DUPLICATE KEY UPDATE amabilidad_chat=$amabilidad,eficiencia_chat=$eficiencia,cantidad_chat=$cantidad,cantidad_contestados_chat=$cantidad_contestados";
		mysqli_query($link,$query);
	}
	
	foreach($evaluaciones_ticket as $operador => $valores)
	{
		$operador = utf8_decode($operador);
		if(!isset($valores["amabilidad"]) && !isset($valores["eficiencia"]) && !isset($valores["cantidad"]))
			$cantidad = (double)$valores;
		else
		{
			$amabilidad = round($valores["amabilidad"],1);
			$eficiencia = round($valores["eficiencia"],1);
			$cantidad = round($valores["cantidad"],1);
			$cantidad_contestados = round($valores["cantidad_contestados"],1);
		}
		
		$query = "INSERT INTO calificaciones (operador,amabilidad_ticket,eficiencia_ticket,cantidad_ticket,cantidad_contestados_ticket,fecha) 
					VALUES ('$operador',$amabilidad,$eficiencia,$cantidad,$cantidad_contestados,'$mes-$año')
					ON DUPLICATE KEY UPDATE amabilidad_ticket=$amabilidad,eficiencia_ticket=$eficiencia,cantidad_ticket=$cantidad,cantidad_contestados_ticket=$cantidad_contestados";
		mysqli_query($link,$query);
	}
	
	foreach($evaluaciones_telefono as $operador => $valores)
	{
		$operador = utf8_decode($operador);
		if(!isset($valores["amabilidad"]) && !isset($valores["eficiencia"]) && !isset($valores["cantidad"]))
			$cantidad = (double)$valores;
		else
		{
			$amabilidad = round($valores["amabilidad"],1);
			$eficiencia = round($valores["eficiencia"],1);
			$cantidad = round($valores["cantidad"],1);
			$cantidad_contestados = round($valores["cantidad_contestados"],1);
		}	
		
		$query = "INSERT INTO calificaciones (operador,amabilidad_telefono,eficiencia_telefono,cantidad_telefono,cantidad_contestados_telefono,fecha) 
					VALUES ('$operador',$amabilidad,$eficiencia,$cantidad,$cantidad_contestados,'$mes-$año')
					ON DUPLICATE KEY UPDATE amabilidad_telefono=$amabilidad,eficiencia_telefono=$eficiencia,cantidad_telefono=$cantidad,cantidad_contestados_telefono=$cantidad_contestados";
		mysqli_query($link,$query);
	}
	
	foreach($evaluaciones_total as $operador => $valores)
	{
		$operador = utf8_decode($operador);
		if(!isset($valores["amabilidad"]) && !isset($valores["eficiencia"]) && !isset($valores["cantidad"]))
			$cantidad = (double)$valores;
		else
		{
			$amabilidad = round($valores["amabilidad"],1);
			$eficiencia = round($valores["eficiencia"],1);
			$cantidad = round($valores["cantidad"],1);
			$cantidad_contestados = round($valores["cantidad_contestados"],1);
		}
		
		$query = "INSERT INTO calificaciones (operador,amabilidad_total,eficiencia_total,cantidad_total,cantidad_contestados_total,fecha) 
					VALUES ('$operador',$amabilidad,$eficiencia,$cantidad,$cantidad_contestados,'$mes-$año')
					ON DUPLICATE KEY UPDATE amabilidad_total=$amabilidad,eficiencia_total=$eficiencia,cantidad_total=$cantidad,cantidad_contestados_total=$cantidad_contestados";
		mysqli_query($link,$query);
	}
	
	mysqli_close($link);
}

//Pone la fila de "TOTAL" y de "Porcentaje de Respuesta" al final del arreglo
function enviarTotalesAlFinal($array)
{
	$v = $array['TOTAL'];
	unset($array['TOTAL']);
	$array['TOTAL'] = $v;
	
	$v = $array['Porcentaje de Respuesta'];
	unset($array['Porcentaje de Respuesta']);
	$array['Porcentaje de Respuesta'] = $v;
	
	$v = $array['Total recibidos'];
	unset($array['Total recibidos']);
	$array['Total recibidos'] = $v;
	
	return $array;
}

//Nombre del operador seg?n su anexo
function NombreOperador($id)
{
	$link = mysqli_connect("190.153.249.226", "root", "hosting.,12", "ASTDB");
	if (mysqli_connect_errno()) {
	    printf("Fall?la conexi?: %s\n", mysqli_connect_error());
	    exit();
	}



 	$query = "SELECT * FROM Operadores WHERE id_fop = '$id'";
 	$result = mysqli_query($link, $query);
 	if(mysqli_num_rows($result) == 0)
 		return  utf8_encode("~ No asignado");
 	$data = mysqli_fetch_array($result, MYSQLI_ASSOC);
 	$nombre = utf8_encode($data["nombre"]." ".$data["apellido"]);
 	return $nombre;

}

?>